/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '4/5/23, 4:35 PM' 
 * Generated by 'u58127406' 
 * Generated on server 'ODAWS03-USW2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.9.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M7P08062020' 
 * Generated on browser 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36' 
 * Generated on web client 'https://odamid-usw2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT-04%253A00&ticket=ST-103533-aaXErDfHtUJK42ZHVdsf-cas' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=WORK.STUDENTLOANS out=WORK.TempSorted2236;
	by STUDENTLOANS_BIN;
run;

proc means data=WORK.TempSorted2236 chartype mean std min max median n 
		vardef=df skewness qmethod=os;
	var AVG_MON_DTI_RAT_PRCNT;
	class BACH_HIGHER_ED_BIN;
	by STUDENTLOANS_BIN;
run;

proc datasets library=WORK noprint;
	delete TempSorted2236;
	run;