/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '4/5/23, 5:55 PM' 
 * Generated by 'u58127406' 
 * Generated on server 'ODAWS03-USW2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.9.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M7P08062020' 
 * Generated on browser 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36' 
 * Generated on web client 'https://odamid-usw2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT-04%253A00&ticket=ST-103533-aaXErDfHtUJK42ZHVdsf-cas' 
 *
 */

ods graphics / reset width=6in height=6in imagemap;

proc sgplot data=WORK.STUDENTLOANS;
	title height=12pt "Average Monthly DTI Ratio As Percentage For Americans With & Without Student Loans";
	bubble x=STUDENTLOANS_BIN y=AVG_MON_DTI_RAT_PRCNT size=BACH_HIGHER_ED_BIN/ 
		group=BACH_HIGHER_ED_BIN bradiusmin=5 bradiusmax=10;
	xaxis grid label="Student Loans- Binary";
	yaxis max=500 grid label="Average Monthly DTI Ratio As Percentage (%)";
run;

ods graphics / reset;
title;