/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '4/5/23, 6:21 PM' 
 * Generated by 'u58127406' 
 * Generated on server 'ODAWS03-USW2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.9.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M7P08062020' 
 * Generated on browser 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36' 
 * Generated on web client 'https://odamid-usw2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT-04%253A00&ticket=ST-103533-aaXErDfHtUJK42ZHVdsf-cas' 
 *
 */

/* Define Pie template */
proc template;
	define statgraph SASStudio.Pie;
		begingraph;
		entrytitle "Comparison of Percentages for Americans With/Without Children, Based on Having/Not Having Student Loans (2023)" 
			/ textattrs=(size=16);
		entryfootnote halign=left 
			"0 = Do Not Have Student Loans, 1 = Have Student Loans" / 
			textattrs=(size=12);
		layout region;
		piechart category='CHILDREN?'n / group=STUDENTLOANS_BIN groupgap=2% stat=pct 
			datalabellocation=inside dataskin=pressed;
		endlayout;
		endgraph;
	end;
run;

ods graphics / reset width=12in height=12in imagemap;

proc sgrender template=SASStudio.Pie data=WORK.STUDENTLOANS;
run;

ods graphics / reset;